import { Vue } from "vue-property-decorator";
import { DraggableHelper } from "../draggable_helper";
import { ResizableHelper } from "../resizable_helper";
import { WindowStyle } from "../style";
import { ZElement } from "../z_element";
export declare class WindowType extends Vue {
    isOpen: boolean;
    title: string;
    closeButton: boolean;
    resizable: boolean;
    isScrollable: boolean;
    activateWhenOpen: boolean;
    initialPosition: string;
    zGroup: number;
    windowStyle: WindowStyle;
    private zIndex;
    draggableHelper: DraggableHelper;
    resizableHelper: ResizableHelper;
    zElement: ZElement;
    mounted(): void;
    beforeDestroy(): void;
    windowElement(): HTMLElement;
    titlebarElement(): HTMLElement;
    contentElement(): HTMLElement;
    activate(): void;
    readonly styleWindow: {
        zIndex: string;
        alignContent?: string | null | undefined;
        alignItems?: string | null | undefined;
        alignmentBaseline?: string | null | undefined;
        alignSelf?: string | null | undefined;
        animation?: string | null | undefined;
        animationDelay?: string | null | undefined;
        animationDirection?: string | null | undefined;
        animationDuration?: string | null | undefined;
        animationFillMode?: string | null | undefined;
        animationIterationCount?: string | null | undefined;
        animationName?: string | null | undefined;
        animationPlayState?: string | null | undefined;
        animationTimingFunction?: string | null | undefined;
        backfaceVisibility?: string | null | undefined;
        background?: string | null | undefined;
        backgroundAttachment?: string | null | undefined;
        backgroundClip?: string | null | undefined;
        backgroundColor?: string | null | undefined;
        backgroundImage?: string | null | undefined;
        backgroundOrigin?: string | null | undefined;
        backgroundPosition?: string | null | undefined;
        backgroundPositionX?: string | null | undefined;
        backgroundPositionY?: string | null | undefined;
        backgroundRepeat?: string | null | undefined;
        backgroundSize?: string | null | undefined;
        baselineShift?: string | null | undefined;
        border?: string | null | undefined;
        borderBottom?: string | null | undefined;
        borderBottomColor?: string | null | undefined;
        borderBottomLeftRadius?: string | null | undefined;
        borderBottomRightRadius?: string | null | undefined;
        borderBottomStyle?: string | null | undefined;
        borderBottomWidth?: string | null | undefined;
        borderCollapse?: string | null | undefined;
        borderColor?: string | null | undefined;
        borderImage?: string | null | undefined;
        borderImageOutset?: string | null | undefined;
        borderImageRepeat?: string | null | undefined;
        borderImageSlice?: string | null | undefined;
        borderImageSource?: string | null | undefined;
        borderImageWidth?: string | null | undefined;
        borderLeft?: string | null | undefined;
        borderLeftColor?: string | null | undefined;
        borderLeftStyle?: string | null | undefined;
        borderLeftWidth?: string | null | undefined;
        borderRadius?: string | null | undefined;
        borderRight?: string | null | undefined;
        borderRightColor?: string | null | undefined;
        borderRightStyle?: string | null | undefined;
        borderRightWidth?: string | null | undefined;
        borderSpacing?: string | null | undefined;
        borderStyle?: string | null | undefined;
        borderTop?: string | null | undefined;
        borderTopColor?: string | null | undefined;
        borderTopLeftRadius?: string | null | undefined;
        borderTopRightRadius?: string | null | undefined;
        borderTopStyle?: string | null | undefined;
        borderTopWidth?: string | null | undefined;
        borderWidth?: string | null | undefined;
        bottom?: string | null | undefined;
        boxShadow?: string | null | undefined;
        boxSizing?: string | null | undefined;
        breakAfter?: string | null | undefined;
        breakBefore?: string | null | undefined;
        breakInside?: string | null | undefined;
        captionSide?: string | null | undefined;
        clear?: string | null | undefined;
        clip?: string | null | undefined;
        clipPath?: string | null | undefined;
        clipRule?: string | null | undefined;
        color?: string | null | undefined;
        colorInterpolationFilters?: string | null | undefined;
        columnCount?: any;
        columnFill?: string | null | undefined;
        columnGap?: any;
        columnRule?: string | null | undefined;
        columnRuleColor?: any;
        columnRuleStyle?: string | null | undefined;
        columnRuleWidth?: any;
        columns?: string | null | undefined;
        columnSpan?: string | null | undefined;
        columnWidth?: any;
        content?: string | null | undefined;
        counterIncrement?: string | null | undefined;
        counterReset?: string | null | undefined;
        cssFloat?: string | null | undefined;
        cssText?: string | undefined;
        cursor?: string | null | undefined;
        direction?: string | null | undefined;
        display?: string | null | undefined;
        dominantBaseline?: string | null | undefined;
        emptyCells?: string | null | undefined;
        enableBackground?: string | null | undefined;
        fill?: string | null | undefined;
        fillOpacity?: string | null | undefined;
        fillRule?: string | null | undefined;
        filter?: string | null | undefined;
        flex?: string | null | undefined;
        flexBasis?: string | null | undefined;
        flexDirection?: string | null | undefined;
        flexFlow?: string | null | undefined;
        flexGrow?: string | null | undefined;
        flexShrink?: string | null | undefined;
        flexWrap?: string | null | undefined;
        floodColor?: string | null | undefined;
        floodOpacity?: string | null | undefined;
        font?: string | null | undefined;
        fontFamily?: string | null | undefined;
        fontFeatureSettings?: string | null | undefined;
        fontSize?: string | null | undefined;
        fontSizeAdjust?: string | null | undefined;
        fontStretch?: string | null | undefined;
        fontStyle?: string | null | undefined;
        fontVariant?: string | null | undefined;
        fontWeight?: string | null | undefined;
        glyphOrientationHorizontal?: string | null | undefined;
        glyphOrientationVertical?: string | null | undefined;
        height?: string | null | undefined;
        imeMode?: string | null | undefined;
        justifyContent?: string | null | undefined;
        kerning?: string | null | undefined;
        layoutGrid?: string | null | undefined;
        layoutGridChar?: string | null | undefined;
        layoutGridLine?: string | null | undefined;
        layoutGridMode?: string | null | undefined;
        layoutGridType?: string | null | undefined;
        left?: string | null | undefined;
        length?: number | undefined;
        letterSpacing?: string | null | undefined;
        lightingColor?: string | null | undefined;
        lineBreak?: string | null | undefined;
        lineHeight?: string | null | undefined;
        listStyle?: string | null | undefined;
        listStyleImage?: string | null | undefined;
        listStylePosition?: string | null | undefined;
        listStyleType?: string | null | undefined;
        margin?: string | null | undefined;
        marginBottom?: string | null | undefined;
        marginLeft?: string | null | undefined;
        marginRight?: string | null | undefined;
        marginTop?: string | null | undefined;
        marker?: string | null | undefined;
        markerEnd?: string | null | undefined;
        markerMid?: string | null | undefined;
        markerStart?: string | null | undefined;
        mask?: string | null | undefined;
        maxHeight?: string | null | undefined;
        maxWidth?: string | null | undefined;
        minHeight?: string | null | undefined;
        minWidth?: string | null | undefined;
        msContentZoomChaining?: string | null | undefined;
        msContentZooming?: string | null | undefined;
        msContentZoomLimit?: string | null | undefined;
        msContentZoomLimitMax?: any;
        msContentZoomLimitMin?: any;
        msContentZoomSnap?: string | null | undefined;
        msContentZoomSnapPoints?: string | null | undefined;
        msContentZoomSnapType?: string | null | undefined;
        msFlowFrom?: string | null | undefined;
        msFlowInto?: string | null | undefined;
        msFontFeatureSettings?: string | null | undefined;
        msGridColumn?: any;
        msGridColumnAlign?: string | null | undefined;
        msGridColumns?: string | null | undefined;
        msGridColumnSpan?: any;
        msGridRow?: any;
        msGridRowAlign?: string | null | undefined;
        msGridRows?: string | null | undefined;
        msGridRowSpan?: any;
        msHighContrastAdjust?: string | null | undefined;
        msHyphenateLimitChars?: string | null | undefined;
        msHyphenateLimitLines?: any;
        msHyphenateLimitZone?: any;
        msHyphens?: string | null | undefined;
        msImeAlign?: string | null | undefined;
        msOverflowStyle?: string | null | undefined;
        msScrollChaining?: string | null | undefined;
        msScrollLimit?: string | null | undefined;
        msScrollLimitXMax?: any;
        msScrollLimitXMin?: any;
        msScrollLimitYMax?: any;
        msScrollLimitYMin?: any;
        msScrollRails?: string | null | undefined;
        msScrollSnapPointsX?: string | null | undefined;
        msScrollSnapPointsY?: string | null | undefined;
        msScrollSnapType?: string | null | undefined;
        msScrollSnapX?: string | null | undefined;
        msScrollSnapY?: string | null | undefined;
        msScrollTranslation?: string | null | undefined;
        msTextCombineHorizontal?: string | null | undefined;
        msTextSizeAdjust?: any;
        msTouchAction?: string | null | undefined;
        msTouchSelect?: string | null | undefined;
        msUserSelect?: string | null | undefined;
        msWrapFlow?: string | undefined;
        msWrapMargin?: any;
        msWrapThrough?: string | undefined;
        opacity?: string | null | undefined;
        order?: string | null | undefined;
        orphans?: string | null | undefined;
        outline?: string | null | undefined;
        outlineColor?: string | null | undefined;
        outlineOffset?: string | null | undefined;
        outlineStyle?: string | null | undefined;
        outlineWidth?: string | null | undefined;
        overflow?: string | null | undefined;
        overflowX?: string | null | undefined;
        overflowY?: string | null | undefined;
        padding?: string | null | undefined;
        paddingBottom?: string | null | undefined;
        paddingLeft?: string | null | undefined;
        paddingRight?: string | null | undefined;
        paddingTop?: string | null | undefined;
        pageBreakAfter?: string | null | undefined;
        pageBreakBefore?: string | null | undefined;
        pageBreakInside?: string | null | undefined;
        parentRule?: CSSRule | undefined;
        perspective?: string | null | undefined;
        perspectiveOrigin?: string | null | undefined;
        pointerEvents?: string | null | undefined;
        position?: string | null | undefined;
        quotes?: string | null | undefined;
        right?: string | null | undefined;
        rotate?: string | null | undefined;
        rubyAlign?: string | null | undefined;
        rubyOverhang?: string | null | undefined;
        rubyPosition?: string | null | undefined;
        scale?: string | null | undefined;
        stopColor?: string | null | undefined;
        stopOpacity?: string | null | undefined;
        stroke?: string | null | undefined;
        strokeDasharray?: string | null | undefined;
        strokeDashoffset?: string | null | undefined;
        strokeLinecap?: string | null | undefined;
        strokeLinejoin?: string | null | undefined;
        strokeMiterlimit?: string | null | undefined;
        strokeOpacity?: string | null | undefined;
        strokeWidth?: string | null | undefined;
        tableLayout?: string | null | undefined;
        textAlign?: string | null | undefined;
        textAlignLast?: string | null | undefined;
        textAnchor?: string | null | undefined;
        textDecoration?: string | null | undefined;
        textIndent?: string | null | undefined;
        textJustify?: string | null | undefined;
        textKashida?: string | null | undefined;
        textKashidaSpace?: string | null | undefined;
        textOverflow?: string | null | undefined;
        textShadow?: string | null | undefined;
        textTransform?: string | null | undefined;
        textUnderlinePosition?: string | null | undefined;
        top?: string | null | undefined;
        touchAction?: string | null | undefined;
        transform?: string | null | undefined;
        transformOrigin?: string | null | undefined;
        transformStyle?: string | null | undefined;
        transition?: string | null | undefined;
        transitionDelay?: string | null | undefined;
        transitionDuration?: string | null | undefined;
        transitionProperty?: string | null | undefined;
        transitionTimingFunction?: string | null | undefined;
        translate?: string | null | undefined;
        unicodeBidi?: string | null | undefined;
        verticalAlign?: string | null | undefined;
        visibility?: string | null | undefined;
        webkitAlignContent?: string | null | undefined;
        webkitAlignItems?: string | null | undefined;
        webkitAlignSelf?: string | null | undefined;
        webkitAnimation?: string | null | undefined;
        webkitAnimationDelay?: string | null | undefined;
        webkitAnimationDirection?: string | null | undefined;
        webkitAnimationDuration?: string | null | undefined;
        webkitAnimationFillMode?: string | null | undefined;
        webkitAnimationIterationCount?: string | null | undefined;
        webkitAnimationName?: string | null | undefined;
        webkitAnimationPlayState?: string | null | undefined;
        webkitAnimationTimingFunction?: string | null | undefined;
        webkitAppearance?: string | null | undefined;
        webkitBackfaceVisibility?: string | null | undefined;
        webkitBackgroundClip?: string | null | undefined;
        webkitBackgroundOrigin?: string | null | undefined;
        webkitBackgroundSize?: string | null | undefined;
        webkitBorderBottomLeftRadius?: string | null | undefined;
        webkitBorderBottomRightRadius?: string | null | undefined;
        webkitBorderImage?: string | null | undefined;
        webkitBorderRadius?: string | null | undefined;
        webkitBorderTopLeftRadius?: string | null | undefined;
        webkitBorderTopRightRadius?: string | null | undefined;
        webkitBoxAlign?: string | null | undefined;
        webkitBoxDirection?: string | null | undefined;
        webkitBoxFlex?: string | null | undefined;
        webkitBoxOrdinalGroup?: string | null | undefined;
        webkitBoxOrient?: string | null | undefined;
        webkitBoxPack?: string | null | undefined;
        webkitBoxSizing?: string | null | undefined;
        webkitColumnBreakAfter?: string | null | undefined;
        webkitColumnBreakBefore?: string | null | undefined;
        webkitColumnBreakInside?: string | null | undefined;
        webkitColumnCount?: any;
        webkitColumnGap?: any;
        webkitColumnRule?: string | null | undefined;
        webkitColumnRuleColor?: any;
        webkitColumnRuleStyle?: string | null | undefined;
        webkitColumnRuleWidth?: any;
        webkitColumns?: string | null | undefined;
        webkitColumnSpan?: string | null | undefined;
        webkitColumnWidth?: any;
        webkitFilter?: string | null | undefined;
        webkitFlex?: string | null | undefined;
        webkitFlexBasis?: string | null | undefined;
        webkitFlexDirection?: string | null | undefined;
        webkitFlexFlow?: string | null | undefined;
        webkitFlexGrow?: string | null | undefined;
        webkitFlexShrink?: string | null | undefined;
        webkitFlexWrap?: string | null | undefined;
        webkitJustifyContent?: string | null | undefined;
        webkitOrder?: string | null | undefined;
        webkitPerspective?: string | null | undefined;
        webkitPerspectiveOrigin?: string | null | undefined;
        webkitTapHighlightColor?: string | null | undefined;
        webkitTextFillColor?: string | null | undefined;
        webkitTextSizeAdjust?: any;
        webkitTextStroke?: string | null | undefined;
        webkitTextStrokeColor?: string | null | undefined;
        webkitTextStrokeWidth?: string | null | undefined;
        webkitTransform?: string | null | undefined;
        webkitTransformOrigin?: string | null | undefined;
        webkitTransformStyle?: string | null | undefined;
        webkitTransition?: string | null | undefined;
        webkitTransitionDelay?: string | null | undefined;
        webkitTransitionDuration?: string | null | undefined;
        webkitTransitionProperty?: string | null | undefined;
        webkitTransitionTimingFunction?: string | null | undefined;
        webkitUserModify?: string | null | undefined;
        webkitUserSelect?: string | null | undefined;
        webkitWritingMode?: string | null | undefined;
        whiteSpace?: string | null | undefined;
        widows?: string | null | undefined;
        width?: string | null | undefined;
        wordBreak?: string | null | undefined;
        wordSpacing?: string | null | undefined;
        wordWrap?: string | null | undefined;
        writingMode?: string | null | undefined;
        zoom?: string | null | undefined;
        resize?: string | null | undefined;
        userSelect?: string | null | undefined;
        getPropertyPriority?: ((propertyName: string) => string) | undefined;
        getPropertyValue?: ((propertyName: string) => string) | undefined;
        item?: ((index: number) => string) | undefined;
        removeProperty?: ((propertyName: string) => string) | undefined;
        setProperty?: ((propertyName: string, value: string | null, priority?: string | undefined) => void) | undefined;
    };
    readonly styleTitlebar: Partial<CSSStyleDeclaration>;
    readonly styleContent: {
        alignContent?: string | null | undefined;
        alignItems?: string | null | undefined;
        alignmentBaseline?: string | null | undefined;
        alignSelf?: string | null | undefined;
        animation?: string | null | undefined;
        animationDelay?: string | null | undefined;
        animationDirection?: string | null | undefined;
        animationDuration?: string | null | undefined;
        animationFillMode?: string | null | undefined;
        animationIterationCount?: string | null | undefined;
        animationName?: string | null | undefined;
        animationPlayState?: string | null | undefined;
        animationTimingFunction?: string | null | undefined;
        backfaceVisibility?: string | null | undefined;
        background?: string | null | undefined;
        backgroundAttachment?: string | null | undefined;
        backgroundClip?: string | null | undefined;
        backgroundColor?: string | null | undefined;
        backgroundImage?: string | null | undefined;
        backgroundOrigin?: string | null | undefined;
        backgroundPosition?: string | null | undefined;
        backgroundPositionX?: string | null | undefined;
        backgroundPositionY?: string | null | undefined;
        backgroundRepeat?: string | null | undefined;
        backgroundSize?: string | null | undefined;
        baselineShift?: string | null | undefined;
        border?: string | null | undefined;
        borderBottom?: string | null | undefined;
        borderBottomColor?: string | null | undefined;
        borderBottomLeftRadius?: string | null | undefined;
        borderBottomRightRadius?: string | null | undefined;
        borderBottomStyle?: string | null | undefined;
        borderBottomWidth?: string | null | undefined;
        borderCollapse?: string | null | undefined;
        borderColor?: string | null | undefined;
        borderImage?: string | null | undefined;
        borderImageOutset?: string | null | undefined;
        borderImageRepeat?: string | null | undefined;
        borderImageSlice?: string | null | undefined;
        borderImageSource?: string | null | undefined;
        borderImageWidth?: string | null | undefined;
        borderLeft?: string | null | undefined;
        borderLeftColor?: string | null | undefined;
        borderLeftStyle?: string | null | undefined;
        borderLeftWidth?: string | null | undefined;
        borderRadius?: string | null | undefined;
        borderRight?: string | null | undefined;
        borderRightColor?: string | null | undefined;
        borderRightStyle?: string | null | undefined;
        borderRightWidth?: string | null | undefined;
        borderSpacing?: string | null | undefined;
        borderStyle?: string | null | undefined;
        borderTop?: string | null | undefined;
        borderTopColor?: string | null | undefined;
        borderTopLeftRadius?: string | null | undefined;
        borderTopRightRadius?: string | null | undefined;
        borderTopStyle?: string | null | undefined;
        borderTopWidth?: string | null | undefined;
        borderWidth?: string | null | undefined;
        bottom?: string | null | undefined;
        boxShadow?: string | null | undefined;
        boxSizing?: string | null | undefined;
        breakAfter?: string | null | undefined;
        breakBefore?: string | null | undefined;
        breakInside?: string | null | undefined;
        captionSide?: string | null | undefined;
        clear?: string | null | undefined;
        clip?: string | null | undefined;
        clipPath?: string | null | undefined;
        clipRule?: string | null | undefined;
        color?: string | null | undefined;
        colorInterpolationFilters?: string | null | undefined;
        columnCount?: any;
        columnFill?: string | null | undefined;
        columnGap?: any;
        columnRule?: string | null | undefined;
        columnRuleColor?: any;
        columnRuleStyle?: string | null | undefined;
        columnRuleWidth?: any;
        columns?: string | null | undefined;
        columnSpan?: string | null | undefined;
        columnWidth?: any;
        content?: string | null | undefined;
        counterIncrement?: string | null | undefined;
        counterReset?: string | null | undefined;
        cssFloat?: string | null | undefined;
        cssText?: string | undefined;
        cursor?: string | null | undefined;
        direction?: string | null | undefined;
        display?: string | null | undefined;
        dominantBaseline?: string | null | undefined;
        emptyCells?: string | null | undefined;
        enableBackground?: string | null | undefined;
        fill?: string | null | undefined;
        fillOpacity?: string | null | undefined;
        fillRule?: string | null | undefined;
        filter?: string | null | undefined;
        flex?: string | null | undefined;
        flexBasis?: string | null | undefined;
        flexDirection?: string | null | undefined;
        flexFlow?: string | null | undefined;
        flexGrow?: string | null | undefined;
        flexShrink?: string | null | undefined;
        flexWrap?: string | null | undefined;
        floodColor?: string | null | undefined;
        floodOpacity?: string | null | undefined;
        font?: string | null | undefined;
        fontFamily?: string | null | undefined;
        fontFeatureSettings?: string | null | undefined;
        fontSize?: string | null | undefined;
        fontSizeAdjust?: string | null | undefined;
        fontStretch?: string | null | undefined;
        fontStyle?: string | null | undefined;
        fontVariant?: string | null | undefined;
        fontWeight?: string | null | undefined;
        glyphOrientationHorizontal?: string | null | undefined;
        glyphOrientationVertical?: string | null | undefined;
        height?: string | null | undefined;
        imeMode?: string | null | undefined;
        justifyContent?: string | null | undefined;
        kerning?: string | null | undefined;
        layoutGrid?: string | null | undefined;
        layoutGridChar?: string | null | undefined;
        layoutGridLine?: string | null | undefined;
        layoutGridMode?: string | null | undefined;
        layoutGridType?: string | null | undefined;
        left?: string | null | undefined;
        length?: number | undefined;
        letterSpacing?: string | null | undefined;
        lightingColor?: string | null | undefined;
        lineBreak?: string | null | undefined;
        lineHeight?: string | null | undefined;
        listStyle?: string | null | undefined;
        listStyleImage?: string | null | undefined;
        listStylePosition?: string | null | undefined;
        listStyleType?: string | null | undefined;
        margin?: string | null | undefined;
        marginBottom?: string | null | undefined;
        marginLeft?: string | null | undefined;
        marginRight?: string | null | undefined;
        marginTop?: string | null | undefined;
        marker?: string | null | undefined;
        markerEnd?: string | null | undefined;
        markerMid?: string | null | undefined;
        markerStart?: string | null | undefined;
        mask?: string | null | undefined;
        maxHeight?: string | null | undefined;
        maxWidth?: string | null | undefined;
        minHeight?: string | null | undefined;
        minWidth?: string | null | undefined;
        msContentZoomChaining?: string | null | undefined;
        msContentZooming?: string | null | undefined;
        msContentZoomLimit?: string | null | undefined;
        msContentZoomLimitMax?: any;
        msContentZoomLimitMin?: any;
        msContentZoomSnap?: string | null | undefined;
        msContentZoomSnapPoints?: string | null | undefined;
        msContentZoomSnapType?: string | null | undefined;
        msFlowFrom?: string | null | undefined;
        msFlowInto?: string | null | undefined;
        msFontFeatureSettings?: string | null | undefined;
        msGridColumn?: any;
        msGridColumnAlign?: string | null | undefined;
        msGridColumns?: string | null | undefined;
        msGridColumnSpan?: any;
        msGridRow?: any;
        msGridRowAlign?: string | null | undefined;
        msGridRows?: string | null | undefined;
        msGridRowSpan?: any;
        msHighContrastAdjust?: string | null | undefined;
        msHyphenateLimitChars?: string | null | undefined;
        msHyphenateLimitLines?: any;
        msHyphenateLimitZone?: any;
        msHyphens?: string | null | undefined;
        msImeAlign?: string | null | undefined;
        msOverflowStyle?: string | null | undefined;
        msScrollChaining?: string | null | undefined;
        msScrollLimit?: string | null | undefined;
        msScrollLimitXMax?: any;
        msScrollLimitXMin?: any;
        msScrollLimitYMax?: any;
        msScrollLimitYMin?: any;
        msScrollRails?: string | null | undefined;
        msScrollSnapPointsX?: string | null | undefined;
        msScrollSnapPointsY?: string | null | undefined;
        msScrollSnapType?: string | null | undefined;
        msScrollSnapX?: string | null | undefined;
        msScrollSnapY?: string | null | undefined;
        msScrollTranslation?: string | null | undefined;
        msTextCombineHorizontal?: string | null | undefined;
        msTextSizeAdjust?: any;
        msTouchAction?: string | null | undefined;
        msTouchSelect?: string | null | undefined;
        msUserSelect?: string | null | undefined;
        msWrapFlow?: string | undefined;
        msWrapMargin?: any;
        msWrapThrough?: string | undefined;
        opacity?: string | null | undefined;
        order?: string | null | undefined;
        orphans?: string | null | undefined;
        outline?: string | null | undefined;
        outlineColor?: string | null | undefined;
        outlineOffset?: string | null | undefined;
        outlineStyle?: string | null | undefined;
        outlineWidth?: string | null | undefined;
        overflow?: string | null | undefined;
        overflowX?: string | null | undefined;
        overflowY?: string | null | undefined;
        padding?: string | null | undefined;
        paddingBottom?: string | null | undefined;
        paddingLeft?: string | null | undefined;
        paddingRight?: string | null | undefined;
        paddingTop?: string | null | undefined;
        pageBreakAfter?: string | null | undefined;
        pageBreakBefore?: string | null | undefined;
        pageBreakInside?: string | null | undefined;
        parentRule?: CSSRule | undefined;
        perspective?: string | null | undefined;
        perspectiveOrigin?: string | null | undefined;
        pointerEvents?: string | null | undefined;
        position?: string | null | undefined;
        quotes?: string | null | undefined;
        right?: string | null | undefined;
        rotate?: string | null | undefined;
        rubyAlign?: string | null | undefined;
        rubyOverhang?: string | null | undefined;
        rubyPosition?: string | null | undefined;
        scale?: string | null | undefined;
        stopColor?: string | null | undefined;
        stopOpacity?: string | null | undefined;
        stroke?: string | null | undefined;
        strokeDasharray?: string | null | undefined;
        strokeDashoffset?: string | null | undefined;
        strokeLinecap?: string | null | undefined;
        strokeLinejoin?: string | null | undefined;
        strokeMiterlimit?: string | null | undefined;
        strokeOpacity?: string | null | undefined;
        strokeWidth?: string | null | undefined;
        tableLayout?: string | null | undefined;
        textAlign?: string | null | undefined;
        textAlignLast?: string | null | undefined;
        textAnchor?: string | null | undefined;
        textDecoration?: string | null | undefined;
        textIndent?: string | null | undefined;
        textJustify?: string | null | undefined;
        textKashida?: string | null | undefined;
        textKashidaSpace?: string | null | undefined;
        textOverflow?: string | null | undefined;
        textShadow?: string | null | undefined;
        textTransform?: string | null | undefined;
        textUnderlinePosition?: string | null | undefined;
        top?: string | null | undefined;
        touchAction?: string | null | undefined;
        transform?: string | null | undefined;
        transformOrigin?: string | null | undefined;
        transformStyle?: string | null | undefined;
        transition?: string | null | undefined;
        transitionDelay?: string | null | undefined;
        transitionDuration?: string | null | undefined;
        transitionProperty?: string | null | undefined;
        transitionTimingFunction?: string | null | undefined;
        translate?: string | null | undefined;
        unicodeBidi?: string | null | undefined;
        verticalAlign?: string | null | undefined;
        visibility?: string | null | undefined;
        webkitAlignContent?: string | null | undefined;
        webkitAlignItems?: string | null | undefined;
        webkitAlignSelf?: string | null | undefined;
        webkitAnimation?: string | null | undefined;
        webkitAnimationDelay?: string | null | undefined;
        webkitAnimationDirection?: string | null | undefined;
        webkitAnimationDuration?: string | null | undefined;
        webkitAnimationFillMode?: string | null | undefined;
        webkitAnimationIterationCount?: string | null | undefined;
        webkitAnimationName?: string | null | undefined;
        webkitAnimationPlayState?: string | null | undefined;
        webkitAnimationTimingFunction?: string | null | undefined;
        webkitAppearance?: string | null | undefined;
        webkitBackfaceVisibility?: string | null | undefined;
        webkitBackgroundClip?: string | null | undefined;
        webkitBackgroundOrigin?: string | null | undefined;
        webkitBackgroundSize?: string | null | undefined;
        webkitBorderBottomLeftRadius?: string | null | undefined;
        webkitBorderBottomRightRadius?: string | null | undefined;
        webkitBorderImage?: string | null | undefined;
        webkitBorderRadius?: string | null | undefined;
        webkitBorderTopLeftRadius?: string | null | undefined;
        webkitBorderTopRightRadius?: string | null | undefined;
        webkitBoxAlign?: string | null | undefined;
        webkitBoxDirection?: string | null | undefined;
        webkitBoxFlex?: string | null | undefined;
        webkitBoxOrdinalGroup?: string | null | undefined;
        webkitBoxOrient?: string | null | undefined;
        webkitBoxPack?: string | null | undefined;
        webkitBoxSizing?: string | null | undefined;
        webkitColumnBreakAfter?: string | null | undefined;
        webkitColumnBreakBefore?: string | null | undefined;
        webkitColumnBreakInside?: string | null | undefined;
        webkitColumnCount?: any;
        webkitColumnGap?: any;
        webkitColumnRule?: string | null | undefined;
        webkitColumnRuleColor?: any;
        webkitColumnRuleStyle?: string | null | undefined;
        webkitColumnRuleWidth?: any;
        webkitColumns?: string | null | undefined;
        webkitColumnSpan?: string | null | undefined;
        webkitColumnWidth?: any;
        webkitFilter?: string | null | undefined;
        webkitFlex?: string | null | undefined;
        webkitFlexBasis?: string | null | undefined;
        webkitFlexDirection?: string | null | undefined;
        webkitFlexFlow?: string | null | undefined;
        webkitFlexGrow?: string | null | undefined;
        webkitFlexShrink?: string | null | undefined;
        webkitFlexWrap?: string | null | undefined;
        webkitJustifyContent?: string | null | undefined;
        webkitOrder?: string | null | undefined;
        webkitPerspective?: string | null | undefined;
        webkitPerspectiveOrigin?: string | null | undefined;
        webkitTapHighlightColor?: string | null | undefined;
        webkitTextFillColor?: string | null | undefined;
        webkitTextSizeAdjust?: any;
        webkitTextStroke?: string | null | undefined;
        webkitTextStrokeColor?: string | null | undefined;
        webkitTextStrokeWidth?: string | null | undefined;
        webkitTransform?: string | null | undefined;
        webkitTransformOrigin?: string | null | undefined;
        webkitTransformStyle?: string | null | undefined;
        webkitTransition?: string | null | undefined;
        webkitTransitionDelay?: string | null | undefined;
        webkitTransitionDuration?: string | null | undefined;
        webkitTransitionProperty?: string | null | undefined;
        webkitTransitionTimingFunction?: string | null | undefined;
        webkitUserModify?: string | null | undefined;
        webkitUserSelect?: string | null | undefined;
        webkitWritingMode?: string | null | undefined;
        whiteSpace?: string | null | undefined;
        widows?: string | null | undefined;
        width?: string | null | undefined;
        wordBreak?: string | null | undefined;
        wordSpacing?: string | null | undefined;
        wordWrap?: string | null | undefined;
        writingMode?: string | null | undefined;
        zIndex?: string | null | undefined;
        zoom?: string | null | undefined;
        resize?: string | null | undefined;
        userSelect?: string | null | undefined;
        getPropertyPriority?: ((propertyName: string) => string) | undefined;
        getPropertyValue?: ((propertyName: string) => string) | undefined;
        item?: ((index: number) => string) | undefined;
        removeProperty?: ((propertyName: string) => string) | undefined;
        setProperty?: ((propertyName: string, value: string | null, priority?: string | undefined) => void) | undefined;
    };
    onResizableChange(resizable: boolean): void;
    onIsOpenChange(isOpen: boolean): void;
    onZGroupChange(): void;
    private fixPosition();
    private onResizeWindow;
    initialWidth?: number;
    initialHeight?: number;
    private setDimension();
    minWidth: number;
    minHeight: number;
    maxWidth?: number;
    maxHeight?: number;
    private initResizeHelper();
    private onResize();
}
